// Auto-generated by browser/scripts/生成stub.py
// DO NOT EDIT BY HAND. Regenerate with:
//   python3 browser/scripts/生成stub.py
//
// 来源宏：chromium/src/base/record_replay.cc
//   ForEachV8API     —— 22 个非 void 函数
//   ForEachV8APIVoid —— 44 个 void 函数
//
// 全部 __attribute__((weak))，可被 record_real.cc 等文件里的
// 强符号 override。本文件保证所有 V8 API 符号在链接期都有定义，
// 哪怕它的真实实现还没写。

#define WEAK __attribute__((weak))

#include <cstddef>
#include <cstdarg>
#include <cstdint>
#include <string>

// ---------- ForEachV8API：非 void 函数 ----------

extern "C" WEAK bool V8IsRecordingOrReplaying(const char* feature, const char* subfeature) { return false; }
extern "C" WEAK bool V8IsRecording() { return false; }
extern "C" WEAK bool V8IsReplaying() { return false; }
extern "C" WEAK char* V8GetRecordingId() { return nullptr; }
extern "C" WEAK uintptr_t V8RecordReplayValue(const char* why, uintptr_t value) { return value; }
extern "C" WEAK size_t V8RecordReplayCreateOrderedLock(const char* name) { return 0; }
extern "C" WEAK uint64_t V8RecordReplayNewBookmark() { return 0; }
extern "C" WEAK bool V8RecordReplayAreEventsDisallowed(const char* why) { return false; }
extern "C" WEAK bool V8RecordReplayAreEventsPassedThrough(const char* why) { return false; }
extern "C" WEAK bool V8RecordReplayHasDivergedFromRecording() { return false; }
extern "C" WEAK bool V8RecordReplayUpdateDependencyGraph() { return false; }
extern "C" WEAK int V8RecordReplayNewDependencyGraphNode(const char* json) { return 0; }
extern "C" WEAK bool V8RecordReplayAllowSideEffects() { return true; }
extern "C" WEAK int V8RecordReplayPointerId(const void* ptr) { return 0; }
extern "C" WEAK void* V8RecordReplayIdPointer(int id) { return nullptr; }
extern "C" WEAK bool V8RecordReplayFeatureEnabled(const char* feature, const char* subfeature) { return true; }
extern "C" WEAK bool V8RecordReplayHasDisabledFeatures() { return false; }
extern "C" WEAK bool V8RecordReplayAreAssertsDisabled() { return false; }
extern "C" WEAK bool V8IsMainThread() { return false; }
extern "C" WEAK bool V8RecordReplayIsInReplayCode(const char* why) { return false; }
extern "C" WEAK bool V8RecordReplayHasAsserts() { return false; }
extern "C" WEAK bool V8RecordReplayHadMismatch() { return false; }

// ---------- ForEachV8APIVoid：void 函数 ----------

extern "C" WEAK void V8RecordReplayAssertVA(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayAssertMaybeEventsDisallowedVA(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayAssertBytes(const char* why, const void* buf, size_t size) {}
extern "C" WEAK void V8RecordReplayPrintVA(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayDiagnosticVA(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayCommandDiagnosticVA(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayCommandDiagnosticTraceVA(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayWarning(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayTrace(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayCrash(const char* format, va_list args) {}
extern "C" WEAK void V8RecordReplayBytes(const char* why, void* buf, size_t size) {}
extern "C" WEAK void V8RecordReplayOrderedLock(int lock) {}
extern "C" WEAK void V8RecordReplayOrderedUnlock(int lock) {}
extern "C" WEAK void V8RecordReplayNewCheckpoint() {}
extern "C" WEAK void V8RecordReplayOnAnnotation(const char* kind, const char* contents) {}
extern "C" WEAK void V8RecordReplayOnNetworkRequest(const char* id, const char* kind, uint64_t bookmark) {}
extern "C" WEAK void V8RecordReplayOnNetworkRequestEvent(const char* id) {}
extern "C" WEAK void V8RecordReplayOnNetworkStreamStart(const char* id, const char* kind, const char* parentId) {}
extern "C" WEAK void V8RecordReplayOnNetworkStreamData(const char* id, size_t offset, size_t length, uint64_t bookmark) {}
extern "C" WEAK void V8RecordReplayOnNetworkStreamEnd(const char* id, size_t length) {}
extern "C" WEAK void V8RecordReplayBeginDisallowEvents() {}
extern "C" WEAK void V8RecordReplayBeginDisallowEventsWithLabel(const char* label) {}
extern "C" WEAK void V8RecordReplayEndDisallowEvents() {}
extern "C" WEAK void V8RecordReplayBeginPassThroughEvents() {}
extern "C" WEAK void V8RecordReplayEndPassThroughEvents() {}
extern "C" WEAK void V8RecordReplayRegisterPointer(const char* name, const void* ptr) {}
extern "C" WEAK void V8RecordReplayUnregisterPointer(const void* ptr) {}
extern "C" WEAK void V8RecordReplayBrowserEvent(const char* name, const char* payload) {}
extern "C" WEAK void V8RecordReplayOnEvent(const char* event, bool before) {}
extern "C" WEAK void V8RecordReplayOnMouseEvent(const char* kind, size_t clientX, size_t clientY, bool synthetic) {}
extern "C" WEAK void V8RecordReplayOnKeyEvent(const char* kind, const char* key, bool synthetic) {}
extern "C" WEAK void V8RecordReplayOnNavigationEvent(const char* kind, const char* url) {}
extern "C" WEAK void V8RecordReplayAddDependencyGraphEdge(int source, int target, const char* json) {}
extern "C" WEAK void V8RecordReplayBeginDependencyExecution(int node) {}
extern "C" WEAK void V8RecordReplayEndDependencyExecution() {}
extern "C" WEAK void V8RecordReplayAddOrderedSRWLock(const char* name, void* lock) {}
extern "C" WEAK void V8RecordReplayRemoveOrderedSRWLock(void* lock) {}
extern "C" WEAK void V8RecordReplayMaybeTerminate(void (*callback)(void*), void* data) {}
extern "C" WEAK void V8RecordReplayFinishRecording() {}
extern "C" WEAK void V8RecordReplayGetCurrentJSStack(std::string* stackTrace) {}
extern "C" WEAK void V8RecordReplayEnterReplayCode() {}
extern "C" WEAK void V8RecordReplayExitReplayCode() {}
extern "C" WEAK void V8RecordReplayBeginAssertBufferAllocations(const char* issueLabel) {}
extern "C" WEAK void V8RecordReplayEndAssertBufferAllocations() {}
