#!/usr/bin/env python3
"""
从 chromium/src/base/record_replay.cc 解析 ForEachV8API / ForEachV8APIVoid 宏，
自动生成 browser/driver/src/stubs_v8api.cc —— 包含全部 59 个 V8 侧 extern 符号
的 no-op 实现，全部返回默认值。

用法：
    python3 生成stub.py [chromium_root]

默认 chromium_root = /Users/hongrunhui/Documents/code/chromium

输出文件：browser/driver/src/stubs_v8api.cc

每个非 void 函数生成：
    extern "C" ReturnType Name Formals { return DefaultValue; }
每个 void 函数生成：
    extern "C" void Name Formals {}
"""

import os
import sys
import re
from pathlib import Path


def parse_macro_block(text: str, macro_name: str) -> str:
    """提取 #define <macro_name>(Macro) 的完整 body（连接续行）。"""
    lines = text.split('\n')
    in_block = False
    body_segments = []

    for line in lines:
        if not in_block:
            stripped = line.lstrip()
            head = f'#define {macro_name}(Macro)'
            if stripped.startswith(head):
                rest = stripped[len(head):]
                if rest.rstrip().endswith('\\'):
                    body_segments.append(rest.rstrip()[:-1])
                    in_block = True
                else:
                    return rest
        else:
            stripped_line = line.rstrip()
            if stripped_line.endswith('\\'):
                body_segments.append(stripped_line[:-1])
            else:
                body_segments.append(stripped_line)
                break

    return ' '.join(body_segments)


def parse_macro_calls(body: str):
    """找出 body 中所有顶层 Macro(...) 调用，返回每条的参数列表。"""
    calls = []
    i = 0
    while i < len(body):
        # 找下一个 Macro(
        idx = body.find('Macro(', i)
        if idx == -1:
            break
        # 找匹配的反括号
        j = idx + len('Macro(')
        depth = 1
        args_start = j
        while j < len(body) and depth > 0:
            c = body[j]
            if c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
            j += 1
        if depth != 0:
            print(f'ERROR: unbalanced parens starting at {idx}', file=sys.stderr)
            break
        args_str = body[args_start:j-1]
        args = split_top_level_commas(args_str)
        calls.append([a.strip() for a in args])
        i = j
    return calls


def split_top_level_commas(s: str):
    """按顶层（深度=0）逗号切。"""
    parts = []
    depth = 0
    cur = []
    for c in s:
        if c == '(':
            depth += 1
            cur.append(c)
        elif c == ')':
            depth -= 1
            cur.append(c)
        elif c == ',' and depth == 0:
            parts.append(''.join(cur))
            cur = []
        else:
            cur.append(c)
    if cur:
        last = ''.join(cur).strip()
        if last:
            parts.append(last)
    return parts


def main():
    chromium_root = Path(sys.argv[1]) if len(sys.argv) > 1 \
        else Path('/Users/hongrunhui/Documents/code/chromium')
    src_path = chromium_root / 'src' / 'base' / 'record_replay.cc'
    if not src_path.exists():
        print(f'ERROR: cannot find {src_path}', file=sys.stderr)
        sys.exit(1)

    text = src_path.read_text()
    api_body = parse_macro_block(text, 'ForEachV8API')
    void_body = parse_macro_block(text, 'ForEachV8APIVoid')

    if not api_body:
        print('ERROR: ForEachV8API not found', file=sys.stderr)
        sys.exit(1)
    if not void_body:
        print('ERROR: ForEachV8APIVoid not found', file=sys.stderr)
        sys.exit(1)

    api_calls = parse_macro_calls(api_body)
    void_calls = parse_macro_calls(void_body)

    print(f'INFO: parsed {len(api_calls)} non-void + {len(void_calls)} void '
          f'= {len(api_calls) + len(void_calls)} V8 API extern symbols',
          file=sys.stderr)

    # 生成 stubs_v8api.cc
    out = []
    out.append('// Auto-generated by browser/scripts/生成stub.py')
    out.append('// DO NOT EDIT BY HAND. Regenerate with:')
    out.append('//   python3 browser/scripts/生成stub.py')
    out.append('//')
    out.append('// 来源宏：chromium/src/base/record_replay.cc')
    out.append('//   ForEachV8API     —— %d 个非 void 函数' % len(api_calls))
    out.append('//   ForEachV8APIVoid —— %d 个 void 函数' % len(void_calls))
    out.append('//')
    out.append('// 全部 __attribute__((weak))，可被 record_real.cc 等文件里的')
    out.append('// 强符号 override。本文件保证所有 V8 API 符号在链接期都有定义，')
    out.append('// 哪怕它的真实实现还没写。')
    out.append('')
    out.append('#define WEAK __attribute__((weak))')
    out.append('')
    out.append('#include <cstddef>')
    out.append('#include <cstdarg>')
    out.append('#include <cstdint>')
    out.append('#include <string>')
    out.append('')
    out.append('// ---------- ForEachV8API：非 void 函数 ----------')
    out.append('')

    skipped = 0
    for entry in api_calls:
        if len(entry) != 5:
            print(f'WARN: skipping non-void entry with {len(entry)} fields: {entry}', file=sys.stderr)
            skipped += 1
            continue
        name, formals, _args, ret, default = entry
        out.append(f'extern "C" WEAK {ret} {name}{formals} {{ return {default}; }}')

    out.append('')
    out.append('// ---------- ForEachV8APIVoid：void 函数 ----------')
    out.append('')

    for entry in void_calls:
        if len(entry) != 3:
            print(f'WARN: skipping void entry with {len(entry)} fields: {entry}', file=sys.stderr)
            skipped += 1
            continue
        name, formals, _args = entry
        out.append(f'extern "C" WEAK void {name}{formals} {{}}')

    out.append('')

    if skipped:
        print(f'WARN: skipped {skipped} entries due to parse failures', file=sys.stderr)

    # 输出位置
    repo_root = Path(__file__).resolve().parent.parent  # browser/
    out_path = repo_root / 'driver' / 'src' / 'stubs_v8api.cc'
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(out))
    print(f'INFO: wrote {out_path} ({len(out)} lines)', file=sys.stderr)


if __name__ == '__main__':
    main()
